name: Deploy lambdas to DEV

on:
  push:
    branches:
      - nearform

jobs:
  deploy-nfcs:
    name: Deploy to NFCS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.1'

    - name: Install app dependencies
      run: npm install

    - name: Package lambdas
      run: |
        npm run artifact:create
      env:
        ORG: managed
        BUILD: 0.0.1

    - name: Deploy authorizer
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.NFCS_DEV_KEY }}
        aws_secret_access_key: ${{ secrets.NFCS_DEV_SECRET }}
        aws_region: eu-west-1
        function_name: dev-nfcs-authorizer
        zip_file: lambdas.zip

    - name: Update authorizer alias
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.NFCS_DEV_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.NFCS_DEV_SECRET }}
        AWS_REGION: eu-west-1
      run: ./scripts/update-lambda-alias.sh "dev-nfcs-authorizer" "-live"

    - name: Deploy cleanup
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.NFCS_DEV_KEY }}
        aws_secret_access_key: ${{ secrets.NFCS_DEV_SECRET }}
        aws_region: eu-west-1
        function_name: dev-nfcs-cleanup
        zip_file: lambdas.zip

    - name: Deploy exposures
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.NFCS_DEV_KEY }}
        aws_secret_access_key: ${{ secrets.NFCS_DEV_SECRET }}
        aws_region: eu-west-1
        function_name: dev-nfcs-exposures
        zip_file: lambdas.zip

    - name: Deploy qr
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.NFCS_DEV_KEY }}
        aws_secret_access_key: ${{ secrets.NFCS_DEV_SECRET }}
        aws_region: eu-west-1
        function_name: dev-nfcs-qr
        zip_file: lambdas.zip

    - name: Deploy settings
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.NFCS_DEV_KEY }}
        aws_secret_access_key: ${{ secrets.NFCS_DEV_SECRET }}
        aws_region: eu-west-1
        function_name: dev-nfcs-settings
        zip_file: lambdas.zip

    - name: Deploy token
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.NFCS_DEV_KEY }}
        aws_secret_access_key: ${{ secrets.NFCS_DEV_SECRET }}
        aws_region: eu-west-1
        function_name: dev-nfcs-token
        zip_file: lambdas.zip
